services:
  api:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - ./src/body_insight:/app/body_insight
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: postgresql+psycopg://body_insight_user:36n9zaHuExtB@postgresql/body_insight?options=-csearch_path=body_insight
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - volume_postgresql:/var/lib/postgresql/data
      - ./for_develop/postgresql/init:/docker-entrypoint-initdb.d
    env_file:
      - ./for_develop/postgresql/config/postgresql.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./for_develop/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container_pgadmin
    ports:
      - 5050:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    env_file:
      - ./for_develop/pgadmin/config/pgadmin.env
    depends_on:
      - postgresql

volumes:
  volume_postgresql:
    name: vpg
  volume_pgadmin:
    name: vpga
